<?php

namespace KeeperBundle\Repository;

/**
 * BoitierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoitierRepository extends \Doctrine\ORM\EntityRepository
{
}
