<?php

namespace KeeperBundle\Repository;

/**
 * CoordonneeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoordonneeRepository extends \Doctrine\ORM\EntityRepository
{
}
