<?php

namespace KeeperBundle\Repository;

/**
 * CoordonneesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoordonneesRepository extends \Doctrine\ORM\EntityRepository
{
}
